grab_focus = true

cache_enabled = true

default_finder = desktop
# desktop_prefix = ""
# unicode_prefix = .
# math_prefix = =
# font_prefix = '
# desktop_launch_prefix = ""
desktop_icons = true

window_size = 1280 1280