-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "2880x1800@90.00", position = "-32x0", scale = 2.00 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "1408x0", scale = 1.00, mirror = "eDP-1" })
