# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# Base config, shared between all devices. This is where you should put all your general settings, such as keybinds, rules, etc.
source = ./base.conf

#hint `>$ hyprctl monitors all`
$display_name = DP-2
$display_scale = 1.6


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# See https://wiki.hyprland.org/Configuring/Keywords/
monitor = $display_name, preferred, auto, $display_scale, bitdepth, 10
