# Background color. Type: color
background = 0xBB131313

# Base color. Type: color
base = 0xFF1C1C1C

# Text color. Type: color
text = 0xFFE3E3E3

# Alternative base color. Type: color
alternate_base = 0xFF242424

# Bright text color. Type: color
bright_text = 0xFFFFEAF4

# Accent color. Type: color
accent = 0xFF99202C

# Secondary accent color. Type: color
accent_secondary = 0xFFFF99EE

# Font size for H1. Type: int
h1_size = 19

# Font size for H2. Type: int
h2_size = 15

# Font size for H3. Type: int
h3_size = 13

# Font size for regular text elements. Type: int
font_size = 11

# Font size for small text elements. Type: int
small_font_size = 10

# Name of the icon theme to use, empty for "the first found". Type: string
icon_theme = empty

# Name of the font family to use. Type: string
font_family = Sans Serif

# Name of the monospace font family to use. Type: string
font_family_monospace = monospace

# Big rounding in logical px. Type: int
rounding_large = 10

# Small rounding in logical px. Type: int
rounding_small = 5